#if !canImport(ObjectiveC)
import XCTest

extension LexerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LexerTests = [
        ("testScan", testScan),
    ]
}

extension RegularExpressionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RegularExpressionTests = [
        ("testPerformanceExample", testPerformanceExample),
        ("testStar", testStar),
        ("testUnion", testUnion),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(LexerTests.__allTests__LexerTests),
        testCase(RegularExpressionTests.__allTests__RegularExpressionTests),
    ]
}
#endif
